kind: Deployment
apiVersion: apps/v1
metadata:
  name: fiap-food
  labels:
    k8s-app: fiap-food
  annotations:
    deployment.kubernetes.io/revision: '3'
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: fiap-food
  template:
    metadata:
      name: fiap-food
      creationTimestamp: null
      labels:
        k8s-app: fiap-food
    spec:
      containers:
        - name: fiap-food
          image: registry.digitalocean.com/fiap-food-registry/fiap-food:latest
          env:
            - name: MYSQL_HOST
              value: leo-pessoal-do-user-9421695-0.b.db.ondigitalocean.com
            - name: MYSQL_PASSWORD
              value: AVNS_ap_g-5JOgfWvQdn4cIQ
            - name: MYSQL_USER
              value: doadmin
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600