kind: Service
apiVersion: v1
metadata:
  name: fiap-food-service
  labels:
    k8s-app: fiap-food
spec:
  ports:
    - name: tcp-5000-5000-qvlwx
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    k8s-app: fiap-food
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster

