name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Decode Docker Registry Token
      id: docker_login
      run: |
        echo "${{ secrets.DOCKER_BASE64_TOKEN }}" | base64 -d > ${{ github.workspace }}/docker_auth.json
        echo "::set-output name=reg_token::$(cat ${{ github.workspace }}/docker_auth.json)"

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: registry.digitalocean.com/fiap-food-registry/fiap-food:latest
        secrets: |
          DOCKER_CONFIG=${{ github.workspace }}

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_TOKEN }}


    - name: Set up environment variables
      env:
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
      run: |
        cd artefatos\ yaml
        envsubst < deployment.yaml > deployment-prod.yaml

    - name: Deploy to Kubernetes
      run: |
        doctl kubernetes cluster kubeconfig save your-cluster-name
        kubectl apply -f artefatos\ yaml/deployment-prod.yaml
        kubectl apply -f artefatos\ yaml/service.yaml
        kubectl rollout status deployment/fiap-food
        kubectl patch deployment fiap-food -p \
        "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}"